=== Bubz43/ep2e/schemas/system.schema.json
{
  "$ref": "#/definitions/SystemSchema",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "SystemSchema": {
      "additionalProperties": false,
      "properties": {
        "author": {
          "type": "string"
        },
        "compatibleCoreVersion": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "download": {
          "type": "string"
        },
        "esmodules": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "gridDistance": {
          "type": "number"
        },
        "gridUnits": {
          "type": "string"
        },
        "initiative": {
          "type": "string"
        },
        "languages": {
          "items": {
            "additionalProperties": {
              "type": "string"
            },
            "properties": {
              "lang": {
                "type": "string"
              },
              "path": {
                "type": "string"
              }
            },
            "required": [
              "lang",
              "path"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "manifest": {
          "type": "string"
        },
        "minimumCoreVersion": {
          "type": "string"
        },
        "name": {
          "const": "ep2e",
          "type": "string"
        },
        "packs": {
          "items": {
            "additionalProperties": {
              "type": "string"
            },
            "properties": {
              "entity": {
                "enum": [
                  "Actor",
                  "Item",
                  "JournalEntry",
                  "RollTable"
                ],
                "type": "string"
              },
              "label": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "path": {
                "type": "string"
              }
            },
            "required": [
              "entity",
              "label",
              "name",
              "path"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "primaryTokenAttribute": {
          "type": "string"
        },
        "scripts": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "secondaryTokenAttribute": {
          "type": [
            "string",
            "null"
          ]
        },
        "socket": {
          "type": "boolean"
        },
        "styles": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "title": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "version": {
          "type": "number"
        }
      },
      "required": [
        "name",
        "title",
        "description",
        "version",
        "author",
        "languages",
        "gridDistance",
        "gridUnits",
        "minimumCoreVersion"
      ],
      "type": "object"
    }
  }
}

=== Bubz43/ep2e/system.json
{
  "version": 0.66,
  "name": "ep2e",
  "title": "Eclipse Phase 2e",
  "description": "Eclipse Phase 2e Game System.",
  "author": "Bubz",
  "esmodules": ["./build/dist/index.js"],
  "styles": ["./build/dist/global.scss.css"],
  "compatibleCoreVersion": "0.7.9",
  "gridDistance": 1,
  "gridUnits": "m",
  "minimumCoreVersion": "0.7.9",
  "socket": true,
  "manifest": "https://github.com/Bubz43/ep2e/releases/latest/download/system.json",
  "download": "https://github.com/Bubz43/ep2e/releases/latest/download/latest.zip",
  "url": "https://github.com/Bubz43/ep2e",
  "languages": [
    {
      "lang": "en",
      "name": "English",
      "path": "lang/en.json"
    }
  ],
  "packs": [
    {
      "name": "traits",
      "system": "ep2e",
      "label": "Traits",
      "path": "./packs/traits.db",
      "entity": "Item"
    },
    {
      "name": "substances",
      "system": "ep2e",
      "label": "Substances",
      "path": "./packs/substances.db",
      "entity": "Item"
    },
      {
      "name": "railguns",
      "system": "ep2e",
      "label": "Railguns",
      "path": "./packs/railguns.db",
      "entity": "Item"
    },
    {
      "name": "firearms",
      "system": "ep2e",
      "label": "Firearms",
      "path": "./packs/firearms.db",
      "entity": "Item"
    },
    {
      "name": "firearm-ammo",
      "system": "ep2e",
      "label": "Firearm Ammo",
      "path": "./packs/firearm-ammo.db",
      "entity": "Item"
    },
    {
      "name": "armor",
      "system": "ep2e",
      "label": "Armor",
      "path": "./packs/armor.db",
      "entity": "Item"
    },
    {
      "name": "melee-weapons",
      "system": "ep2e",
      "label": "Melee Weapons",
      "path": "./packs/melee-weapons.db",
      "entity": "Item"
    },
    {
      "name": "spray-weapons",
      "system": "ep2e",
      "label": "Spray Weapons",
      "path": "./packs/spray-weapons.db",
      "entity": "Item"
    },
    {
      "name": "seeker-weapons",
      "system": "ep2e",
      "label": "Seeker Weapons",
      "path": "./packs/seeker-weapons.db",
      "entity": "Item"
    },
    {
      "name": "beam-weapons",
      "system": "ep2e",
      "label": "Beam Weapons",
      "path": "./packs/beam-weapons.db",
      "entity": "Item"
    },
    {
      "name": "disorders",
      "system": "ep2e",
      "label": "Disorders",
      "path": "./packs/disorders.db",
      "entity": "Item"
    },
    {
      "name": "weapon-accessories",
      "system": "ep2e",
      "label": "Weapon Accessories",
      "path": "./packs/weapon-accessories.db",
      "entity": "JournalEntry"
    }
  ]
}
